import "@radix-ui/themes/styles.css";
import "../theme-config.css";
import "../globals.css";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import { Container, Theme } from "@radix-ui/themes";
import { Toaster } from "react-hot-toast";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{ variables: { colorPrimary: "#5b5bd6" } }}>
      <html lang="en">
        <body className={inter.variable}>
          <Theme appearance="light" accentColor="iris">
            <Toaster position="top-center" reverseOrder={false} />
            <Navbar />
            <main className="p-5">
              <Container>{children}</Container>
            </main>
          </Theme>
        </body>
      </html>
    </ClerkProvider>
  );
}
